name: CI

concurrency:
  group: QA-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get upgrade
          sudo apt-get -y install cmake llvm clang

      - name: Build and test
        run: |
          export BUILD_TYPE=Debug
          export IS_TEST_BUILD=true
          bash configure.sh

      - name: Generate test coverage report
        run: |
          export DO_OPEN_REPORT=false
          bash generate_coverage_report.sh
      
      - uses: actions/upload-artifact@v3
        with:
          name: Coverage report
          path: coverage/report.html

